TEAM_LOGOS = {
    # Deutschland
    "Bayern Munich": "https://logo.clearbit.com/fcbayern.com",
    "FC Bayern München": "https://logo.clearbit.com/fcbayern.com",
    "Bayern München": "https://logo.clearbit.com/fcbayern.com",
    "Borussia Dortmund": "https://logo.clearbit.com/bvb.de",
    "Bayer 04 Leverkusen": "https://logo.clearbit.com/bayer04.de",
    "RB Leipzig": "https://logo.clearbit.com/rbleipzig.com",
    "Eintracht Frankfurt": "https://logo.clearbit.com/eintracht.de",
    "SC Freiburg": "https://logo.clearbit.com/scfreiburg.com",
    "VfB Stuttgart": "https://logo.clearbit.com/vfb.de",
    "TSG Hoffenheim": "https://logo.clearbit.com/tsg-hoffenheim.de",
    "1. FSV Mainz 05": "https://logo.clearbit.com/mainz05.de",
    "VfL Wolfsburg": "https://logo.clearbit.com/vfl-wolfsburg.de",
    "Borussia Mönchengladbach": "https://logo.clearbit.com/borussia.de",
    "FC Augsburg": "https://logo.clearbit.com/fcaugsburg.de",
    "Werder Bremen": "https://logo.clearbit.com/werder.de",
    "1. FC Union Berlin": "https://logo.clearbit.com/fc-union-berlin.de",
    "Union Berlin": "https://logo.clearbit.com/fc-union-berlin.de",
    "FC St. Pauli": "https://logo.clearbit.com/fcstpauli.com",
    "Holstein Kiel": "https://logo.clearbit.com/holstein-kiel.de",
    "1. FC Heidenheim 1846": "https://logo.clearbit.com/fch1846.de",
    "Heidenheim": "https://logo.clearbit.com/fch1846.de",

    # Schweiz
    "FC Basel 1893": "https://logo.clearbit.com/fcb.ch",
    "FC Basel": "https://logo.clearbit.com/fcb.ch",
    "BSC Young Boys": "https://logo.clearbit.com/bscyb.ch",
    "Young Boys": "https://logo.clearbit.com/bscyb.ch",
    "FC Zürich": "https://logo.clearbit.com/fcz.ch",
    "FC Zurich": "https://logo.clearbit.com/fcz.ch",
    "Servette FC": "https://logo.clearbit.com/servettefc.ch",
    "FC Lugano": "https://logo.clearbit.com/fclugano.com",
    "FC St. Gallen 1879": "https://logo.clearbit.com/fcsg.ch",
    "FC St. Gallen": "https://logo.clearbit.com/fcsg.ch",
    "FC Lausanne-Sport": "https://logo.clearbit.com/lausanne-sport.ch",
    "FC Luzern": "https://logo.clearbit.com/fcl.ch",
    "FC Sion": "https://logo.clearbit.com/fcsion.ch",
    "Grasshopper Club Zürich": "https://logo.clearbit.com/gcz.ch",
    "Grasshopper Club Zurich": "https://logo.clearbit.com/gcz.ch",
    "Yverdon Sport FC": "https://logo.clearbit.com/yverdon-sport.ch",
    "FC Winterthur": "https://logo.clearbit.com/fcw.ch",

    # Oesterreich
    "FC Red Bull Salzburg": "https://logo.clearbit.com/redbullsalzburg.at",
    "Red Bull Salzburg": "https://logo.clearbit.com/redbullsalzburg.at",
    "SK Rapid Wien": "https://logo.clearbit.com/skrapid.at",
    "Rapid Wien": "https://logo.clearbit.com/skrapid.at",
    "FK Austria Wien": "https://logo.clearbit.com/fk-austria.at",
    "Austria Wien": "https://logo.clearbit.com/fk-austria.at",
    "SK Sturm Graz": "https://logo.clearbit.com/sksturm.at",
    "Sturm Graz": "https://logo.clearbit.com/sksturm.at",
    "LASK": "https://logo.clearbit.com/lask.at",
    "VfL Wolfsberger AC": "https://logo.clearbit.com/wac.at",
    "Wolfsberger AC": "https://logo.clearbit.com/wac.at",
    "TSV Hartberg": "https://logo.clearbit.com/tsv-hartberg-fussball.at",
    "FK Austria Klagenfurt": "https://logo.clearbit.com/austriaklagenfurt.at",
    "Austria Klagenfurt": "https://logo.clearbit.com/austriaklagenfurt.at",
    "WSG Tirol": "https://logo.clearbit.com/wsg-fussball.at",
    "SCR Altach": "https://logo.clearbit.com/scra.at",
    "Grazer AK": "https://logo.clearbit.com/grazerak.at",
    "GAK": "https://logo.clearbit.com/grazerak.at",
    "Blau-Weiß Linz": "https://logo.clearbit.com/blauweiss-linz.at",
    "Blau-Weiss Linz": "https://logo.clearbit.com/blauweiss-linz.at",

    # Italien
    "Juventus": "https://logo.clearbit.com/juventus.com",
    "Inter": "https://logo.clearbit.com/inter.it",
    "Inter Milan": "https://logo.clearbit.com/inter.it",
    "AC Milan": "https://logo.clearbit.com/acmilan.com",
    "Milan": "https://logo.clearbit.com/acmilan.com",
    "Napoli": "https://logo.clearbit.com/sscnapoli.it",
    "AS Roma": "https://logo.clearbit.com/asroma.com",
    "Roma": "https://logo.clearbit.com/asroma.com",
    "Lazio": "https://logo.clearbit.com/sslazio.it",
    "SS Lazio": "https://logo.clearbit.com/sslazio.it",
    "Atalanta": "https://logo.clearbit.com/atalanta.it",
    "Bologna": "https://logo.clearbit.com/bolognafc.it",
    "Fiorentina": "https://logo.clearbit.com/acffiorentina.com",
    "Torino": "https://logo.clearbit.com/torinofc.it",
    "Genoa": "https://logo.clearbit.com/genoacfc.it",
    "Como": "https://logo.clearbit.com/comofootball.com",
    "Udinese": "https://logo.clearbit.com/udinese.it",
    "Cagliari": "https://logo.clearbit.com/cagliaricalcio.com",
    "Parma": "https://logo.clearbit.com/parmacalcio1913.com",
    "Hellas Verona": "https://logo.clearbit.com/hellasverona.it",

    # Frankreich
    "Paris Saint-Germain": "https://logo.clearbit.com/psg.fr",
    "PSG": "https://logo.clearbit.com/psg.fr",
    "Olympique de Marseille": "https://logo.clearbit.com/om.fr",
    "Marseille": "https://logo.clearbit.com/om.fr",
    "AS Monaco": "https://logo.clearbit.com/asmonaco.com",
    "Lille OSC": "https://logo.clearbit.com/losc.fr",
    "Lille": "https://logo.clearbit.com/losc.fr",
    "Olympique Lyonnais": "https://logo.clearbit.com/ol.fr",
    "Lyon": "https://logo.clearbit.com/ol.fr",
    "OGC Nice": "https://logo.clearbit.com/ogcnice.com",
    "Nice": "https://logo.clearbit.com/ogcnice.com",
    "RC Lens": "https://logo.clearbit.com/rclens.fr",
    "Lens": "https://logo.clearbit.com/rclens.fr",
    "Stade Rennais FC": "https://logo.clearbit.com/staderennais.com",
    "Rennes": "https://logo.clearbit.com/staderennais.com",
    "Stade Brestois 29": "https://logo.clearbit.com/sb29.bzh",
    "Brest": "https://logo.clearbit.com/sb29.bzh",
    "Toulouse FC": "https://logo.clearbit.com/toulousefc.com",
    "Toulouse": "https://logo.clearbit.com/toulousefc.com",
    "Montpellier HSC": "https://logo.clearbit.com/mhscfoot.com",
    "Montpellier": "https://logo.clearbit.com/mhscfoot.com",
    "Strasbourg": "https://logo.clearbit.com/rcstrasbourgalsace.fr",

    # Nationalteams fuer EURO / WM
    "Germany": "https://flagcdn.com/w80/de.png",
    "France": "https://flagcdn.com/w80/fr.png",
    "Italy": "https://flagcdn.com/w80/it.png",
    "Switzerland": "https://flagcdn.com/w80/ch.png",
    "Austria": "https://flagcdn.com/w80/at.png",
    "England": "https://flagcdn.com/w80/gb-eng.png",
    "Spain": "https://flagcdn.com/w80/es.png",
    "Portugal": "https://flagcdn.com/w80/pt.png",
    "Netherlands": "https://flagcdn.com/w80/nl.png",
    "Belgium": "https://flagcdn.com/w80/be.png",
    "Croatia": "https://flagcdn.com/w80/hr.png",
    "Denmark": "https://flagcdn.com/w80/dk.png",
    "Poland": "https://flagcdn.com/w80/pl.png",
    "Czech Republic": "https://flagcdn.com/w80/cz.png",
    "Hungary": "https://flagcdn.com/w80/hu.png"
}


def get_logo(team_name: str) -> str:
    return TEAM_LOGOS.get(team_name, "https://placehold.co/80x80/1f2a44/ffffff?text=%20")