from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

router = APIRouter()
templates = Jinja2Templates(directory="templates")


@router.get("/", response_class=HTMLResponse)
async def homepage(request: Request, lang: str = "de"):
    translations = {
        "de": {
            "brand": "Football Stats",
            "nav1": "Bundesliga Stats",
            "nav2": "Champions League Stats",
            "nav3": "Premier League Stats",
            "nav4": "EM 2024 Stats",
            "login": "Login",
            "hero_status": "Bundesliga Live Status",
            "possession": "Ballbesitz",
            "shots": "Schüsse gesamt",
            "xg": "xG",
            "team_stats": "Team Statistiken",
            "top_teams": "Top Teams",
            "search_placeholder": "Suche Teams, Spieler oder Statistiken ...",
            "player_stats": "Spieler Statistiken",
            "top_scorer": "Top Scorer",
            "top_assists": "Top Assists",
            "view_full_table": "Gesamte Tabelle ansehen",
            "see_all_teams": "Alle Teams ansehen",
            "view_full_scorers": "Alle Torschützen ansehen",
            "view_all_assists": "Alle Assist-Leader ansehen",
            "trust_title": "Kostenlose Statistiken & Live-Daten",
            "trust_text": "Öffentliche Statistiken schaffen Vertrauen und Sichtbarkeit. Nutzer sehen sofort, dass deine Plattform echten Mehrwert bietet.",
            "premium_title": "Mehr Analysen nach Login",
            "premium_text": "Gewinnwahrscheinlichkeiten, Formmodelle, Head-to-Head Analysen und weitere Premium-Funktionen nach Registrierung.",
            "learn_more": "Mehr erfahren",
            "register_now": "Login / Registrieren",
        },
        "en": {
            "brand": "Football Stats",
            "nav1": "Bundesliga Stats",
            "nav2": "Champions League Stats",
            "nav3": "Premier League Stats",
            "nav4": "Euro 2024 Stats",
            "login": "Login",
            "hero_status": "Bundesliga Live Status",
            "possession": "Ball Possession",
            "shots": "Total Shots",
            "xg": "xG",
            "team_stats": "Team Statistics",
            "top_teams": "Top Teams",
            "search_placeholder": "Search teams, players, or stats ...",
            "player_stats": "Player Statistics",
            "top_scorer": "Top Scorers",
            "top_assists": "Top Assists",
            "view_full_table": "View Full Table",
            "see_all_teams": "See All Teams",
            "view_full_scorers": "View Full Scorers",
            "view_all_assists": "View All Assist Leaders",
            "trust_title": "Free statistics & live data",
            "trust_text": "Public statistics build trust and visibility. Users instantly see that your platform offers real value.",
            "premium_title": "More analysis after login",
            "premium_text": "Win probabilities, form models, head-to-head analysis and further premium features after registration.",
            "learn_more": "Learn more",
            "register_now": "Login / Register",
        },
        "it": {
            "brand": "Football Stats",
            "nav1": "Statistiche Bundesliga",
            "nav2": "Statistiche Champions League",
            "nav3": "Statistiche Premier League",
            "nav4": "Statistiche Euro 2024",
            "login": "Login",
            "hero_status": "Stato Live Bundesliga",
            "possession": "Possesso palla",
            "shots": "Tiri totali",
            "xg": "xG",
            "team_stats": "Statistiche Squadre",
            "top_teams": "Top Squadre",
            "search_placeholder": "Cerca squadre, giocatori o statistiche ...",
            "player_stats": "Statistiche Giocatori",
            "top_scorer": "Migliori Marcatori",
            "top_assists": "Migliori Assist",
            "view_full_table": "Vedi classifica completa",
            "see_all_teams": "Vedi tutte le squadre",
            "view_full_scorers": "Vedi tutti i marcatori",
            "view_all_assists": "Vedi tutti gli assist leader",
            "trust_title": "Statistiche gratuite e dati live",
            "trust_text": "Le statistiche pubbliche creano fiducia e visibilità. Gli utenti vedono subito che la tua piattaforma offre vero valore.",
            "premium_title": "Più analisi dopo il login",
            "premium_text": "Probabilità di vittoria, modelli di forma, analisi testa a testa e altre funzioni premium dopo la registrazione.",
            "learn_more": "Scopri di più",
            "register_now": "Login / Registrati",
        },
        "hu": {
            "brand": "Football Stats",
            "nav1": "Bundesliga statisztikák",
            "nav2": "Bajnokok Ligája statisztikák",
            "nav3": "Premier League statisztikák",
            "nav4": "EB 2024 statisztikák",
            "login": "Belépés",
            "hero_status": "Bundesliga élő állapot",
            "possession": "Labdabirtoklás",
            "shots": "Összes lövés",
            "xg": "xG",
            "team_stats": "Csapat statisztikák",
            "top_teams": "Top csapatok",
            "search_placeholder": "Csapatok, játékosok vagy statisztikák keresése ...",
            "player_stats": "Játékos statisztikák",
            "top_scorer": "Legjobb góllövők",
            "top_assists": "Legjobb gólpasszok",
            "view_full_table": "Teljes tabella megtekintése",
            "see_all_teams": "Összes csapat megtekintése",
            "view_full_scorers": "Összes góllövő megtekintése",
            "view_all_assists": "Összes gólpassz lista",
            "trust_title": "Ingyenes statisztikák és élő adatok",
            "trust_text": "A nyilvános statisztikák bizalmat és láthatóságot építenek. A felhasználók azonnal látják, hogy a platform valódi értéket kínál.",
            "premium_title": "Több elemzés belépés után",
            "premium_text": "Győzelmi valószínűségek, forma modellek, head-to-head elemzések és további prémium funkciók regisztráció után.",
            "learn_more": "További információ",
            "register_now": "Belépés / Regisztráció",
        },
    }

    t = translations.get(lang, translations["de"])

    context = {
        "request": request,
        "lang": lang,
        "t": t,
        "table_rows": [
            ["Bayern Munich", "30", "+39", "65"],
            ["Borussia Dortmund", "30", "+8", "65"],
            ["Bayer Leverkusen", "30", "+6", "64"],
            ["RB Leipzig", "30", "+4", "53"],
        ],
        "top_teams_left": ["Manchester City", "Arsenal", "Inter Milan", "Real Madrid"],
        "top_teams_right": ["Real Madrid", "Inter", "Juventus", "Milan"],
        "scorers": [
            ["H. Kane", "Bayern Munich", "28", "28"],
            ["E. Haaland", "Manchester City", "23", "23"],
            ["Lautaro Martinez", "Inter Milan", "20", "20"],
            ["Kylian Mbappe", "Paris SG", "19", "19"],
            ["V. Boniface", "Bayer Leverkusen", "18", "18"],
        ],
        "assists": [
            ["K. De Bruyne", "Man City", "16", "18"],
            ["L. Sane", "Bayern Munich", "13", "13"],
            ["D. Payet", "Santos", "12", "12"],
            ["S. Druijf", "Slovan Bratislava", "11", "11"],
            ["J. Doku", "Manchester City", "11", "11"],
        ],
    }

    return templates.TemplateResponse("index.html", context)